### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shaggygi**
Fixed correct link for announcements.

### CODE REVIEW

**Comment by nulltoken** [comment]
LGTM :shipit:

**Comment by shaggygi** [comment]
OK, now that's a lot of approvals right there 😄

**Comment by axelheer** [comment]
This is madness!

**Comment by omariom** [comment]
What is going on?

**Comment by tuespetre** [comment]
The health of the entire dotnet ecosystem depends on your approval, @omariom

**Comment by omariom** [comment]
LGTM, though a bit late to the party..

**Pull request merged**
